Resources:
	Ec2Instance:
		Type: AWS::EC2::Instance
		Properties:
			SecurityGroups:
			- Ref: InstanceSecurityGroup
			- MyExistingSecurityGroup
			KeyName: mykey
			ImageId: ami-7a11e213
	InstanceSecurityGroup:
		Type: AWS::EC2::SecurityGroup
		Properties:
			GroupDescription: Enable SSH access via port 22
		SecurityGroupIngress:
		  - IpProtocol: tcp
			FromPort: '22'
			ToPort: '22'
			CidrIp: 0.0.0.0/0


Resources: 
  ec2-instance:
      Type: AWS::EC2::Instance
      Properties:
        SecurityGroups:
        - Ref: InstanceSecurityGroup #La clase InstanceSecurityGroup
        KeyName: mykey
        ImageId: ami-0102022
        SecurityGroupIds:
        - Ref: SecurityGroup
        SubnetId: 
        - Ref: 
        InstanceType: 
        Tags:


"ec2-instance" : {
    "Type" : "AWS::EC2::Instance",
    "Properties" : {
        "ImageId" : "ami-0102022,
        "SecurityGroupIds" : [{ "Ref" : "SecurityGroup" }],
        "SubnetId" : { "Ref" : "Subnet" },
        "InstanceType" : "m1.medium",
        "Tags" : [
            {"Key" : "Name", "Value" : "Instance name"},
            {"Key" : "Environment", "Value" : { "Ref" : "Environment" }},
            {"Key" : "Owner", "Value" : { "Ref" : "Owner" }}
        ]
    }
}